[package]
name = "easy_pool_proc_macro"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/netskillzgh/easy-pool"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.40"
syn = {version = "1.0.98", features = ["full"]}
quote = "1.0.20"